### ISSUE TITLE
deploy versjon som håndterer informasjonsmodeller

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-rdf-postman#20]
Idag kjøres denne kun som `fdk-dataset-postman`, den må også konfigureres til å kunne kjøres i en annen pod som håndterer informasjonsmodeller, feks `fdk-information-model-postman`

Trengs for å oppdatere diff-store med informasjonsmodeller

**Comment by valosnah** [comment]
Arkiverer repo, lukkes
